name: CI/CD Pipeline

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Code
        run: npm run build

  deploy-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    environment: staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          # Insert your actual deployment command for staging here
          # For example, for a static site:
          # npx surge dist/ your-staging-url.surge.sh

  deploy-main:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: main
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Main (Production)
        run: |
          echo "Deploying to main (production) environment..."
          # Insert your actual deployment command for production here
          # For example, publishing to npm:
          # npm publish --access public
